/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 graph33.gltf
Author: evanpoliquin (https://sketchfab.com/evanpoliquin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/graph-3b385029a8b849b7978cfece6c208abd
Title: Graph
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/graph33.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4f594ca4ef6647dface8dc3910e3ee57fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="pCube6" position={[0, -0.532, 2.151]} scale={[8.968, 0.217, 2.988]}>
                  <mesh name="pCube6_WhiteBase_0" geometry={nodes.pCube6_WhiteBase_0.geometry} material={materials.WhiteBase} />
                </group>
                <group name="pCube7" position={[-0.389, 0.057, 1.777]} rotation={[0.018, 0, 0]}>
                  <mesh name="pCube7_PurpleNoRound_0" geometry={nodes.pCube7_PurpleNoRound_0.geometry} material={materials.PurpleNoRound} />
                  <mesh name="pCube7_WhiteBase_0" geometry={nodes.pCube7_WhiteBase_0.geometry} material={materials.WhiteBase} />
                </group>
                <group name="pCube9" position={[-0.613, 0.812, -0.354]}>
                  <mesh name="pCube9_Green_0" geometry={nodes.pCube9_Green_0.geometry} material={materials.Green} />
                  <mesh name="pCube9_WhiteBase_0" geometry={nodes.pCube9_WhiteBase_0.geometry} material={materials.WhiteBase} />
                </group>
                <group name="pPlane1" position={[0, -1.397, 0]} scale={56.037}>
                  <mesh name="pPlane1_Ground_0" geometry={nodes.pPlane1_Ground_0.geometry} material={materials.Ground} />
                </group>
                <group name="LineGraph" position={[-0.863, 0.414, 3.075]}>
                  <group name="pCylinder1" position={[-3.549, 0.003, 0.492]}>
                    <mesh name="pCylinder1_rsMaterial2_0" geometry={nodes.pCylinder1_rsMaterial2_0.geometry} material={materials.rsMaterial2} />
                  </group>
                  <group name="pCylinder2" position={[-2.625, 0.01, -0.34]}>
                    <mesh name="pCylinder2_GlowGraph_0" geometry={nodes.pCylinder2_GlowGraph_0.geometry} material={materials.GlowGraph} />
                  </group>
                  <group name="pCylinder3" position={[-1.578, 0.01, 0.644]}>
                    <mesh name="pCylinder3_GlowGraph_0" geometry={nodes.pCylinder3_GlowGraph_0.geometry} material={materials.GlowGraph} />
                  </group>
                  <group name="pCylinder4" position={[0.408, 0.01, -0.778]}>
                    <mesh name="pCylinder4_GlowGraph_0" geometry={nodes.pCylinder4_GlowGraph_0.geometry} material={materials.GlowGraph} />
                  </group>
                  <group name="pCylinder5" position={[1.586, 0.01, 0.487]}>
                    <mesh name="pCylinder5_GlowGraph_0" geometry={nodes.pCylinder5_GlowGraph_0.geometry} material={materials.GlowGraph} />
                  </group>
                  <group name="pCylinder6" position={[2.763, 0.01, -0.258]}>
                    <mesh name="pCylinder6_GlowGraph_0" geometry={nodes.pCylinder6_GlowGraph_0.geometry} material={materials.GlowGraph} />
                  </group>
                  <group name="pCube8" position={[-0.065, -0.004, 0.01]}>
                    <mesh name="pCube8_PurpleNoRound_0" geometry={nodes.pCube8_PurpleNoRound_0.geometry} material={materials.PurpleNoRound} />
                    <mesh name="pCube8_LighterPurple_0" geometry={nodes.pCube8_LighterPurple_0.geometry} material={materials.LighterPurple} />
                  </group>
                </group>
                <group name="BarGraph" position={[0, 3.304, -4.187]} rotation={[0, 0.001, 0]}>
                  <group name="pCube1" position={[-3, -3.059, 0.187]} scale={[1.607, 5.47, 1.607]}>
                    <mesh name="pCube1_PurpleBars_0" geometry={nodes.pCube1_PurpleBars_0.geometry} material={materials.PurpleBars} />
                  </group>
                  <group name="pCube2" position={[-1, -3.059, 0.187]} scale={[1.607, 6.341, 1.607]}>
                    <mesh name="pCube2_PurpleBars_0" geometry={nodes.pCube2_PurpleBars_0.geometry} material={materials.PurpleBars} />
                  </group>
                  <group name="pCube3" position={[1, -3.059, 0.187]} scale={[1.607, 3.872, 1.607]}>
                    <mesh name="pCube3_PurpleBars_0" geometry={nodes.pCube3_PurpleBars_0.geometry} material={materials.PurpleBars} />
                  </group>
                  <group name="pCube4" position={[3, -3.059, 0.187]} scale={[1.607, 2.6, 1.607]}>
                    <mesh name="pCube4_PurpleBars_0" geometry={nodes.pCube4_PurpleBars_0.geometry} material={materials.PurpleBars} />
                  </group>
                  <group name="pCube10" position={[0, -3.451, 0.01]} scale={[9.02, 0.222, 2.961]}>
                    <mesh name="pCube10_WhiteBase_0" geometry={nodes.pCube10_WhiteBase_0.geometry} material={materials.WhiteBase} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/graph33.gltf')
