import React from "react";
import 'assets/scss/header-aurora.css';
import 'assets/scss/stock-select.css';
import 'assets/scss/styles.css';
import SparkleButton3 from "./sparkleButton3";
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';
import {store, persistor} from './store';
import Discounter from "./intrinsicValuationCourse/discountingFunction.js"

const DiscountedCashFlow = () => {
    return (
        <div>
            <div className="aurora-gradient">
            <div className="header-body">
                <div className="aurora-content">
                <h1 className="aurora-title"> 
                    Discounted Cashflow Valuation
                    <div className="aurora">
                    <div className="aurora__item"></div>
                    <div className="aurora__item"></div>
                    <div className="aurora__item"></div>
                    <div className="aurora__item"></div>
                    </div>
                </h1>
                </div>
            </div>
            </div>
            <div className="card-body">
                <div className='card2'>
                    <div className='card2-content'>
                        <p>
                            <strong>Discounted Cash Flow (DCF) Valuation</strong> is a financial modeling technique used to estimate the intrinsic value of an investment or asset by forecasting and discounting its future cash flows back to their present value. It is widely used in finance and investment analysis, particularly for valuing stocks, bonds, real estate, and businesses. Here are the key concepts of DCF valuation:
                        </p>
                        <ol>
                        <li>
                        <strong>Future Cash Flows:</strong> The core of DCF valuation is the estimation of the future cash flows generated by an investment or asset. These cash flows can include revenues, operating expenses, taxes, and capital expenditures, depending on the type of investment. Cash flows should be projected over a defined time horizon, often referred to as the forecast period.
                        </li>
                        <li>
                        <strong>Time Value of Money (TVM):</strong> DCF recognizes that a dollar received in the future is worth less than a dollar received today due to the opportunity cost of not having that money available for investment elsewhere. To account for this, future cash flows are discounted back to their present value using a discount rate. The TVM principle is expressed by the formula:
                        <br />
                        <code>
                            PV = FV / (1 + r)^n
                        </code>
                        <ul>
                            <li>
                            PV: Present Value
                            </li>
                            <li>
                            FV: Future Value
                            </li>
                            <li>
                            r: Discount Rate (interest rate)
                            </li>
                            <li>
                            n: Number of periods into the future
                            </li>
                        </ul>
                        </li>

                        <li>
                        <strong>Discount Rate:</strong> The discount rate is a critical component of DCF valuation. It represents the required rate of return or the opportunity cost of capital for an investor. The discount rate should reflect the risk associated with the investment. In many cases, the discount rate is composed of two components: the risk-free rate and a risk premium that accounts for the specific risk associated with the investment.
                        </li>

                        <li>
                        <strong>Forecast Period:</strong> DCF models typically have a finite forecast period during which future cash flows are estimated with reasonable accuracy. Beyond this forecast period, analysts often assume a stable or perpetual growth rate for cash flows, known as the perpetuity growth rate.
                        </li>
                        <li>
                        <strong>Perpetuity Growth Rate:</strong> This rate represents the expected long-term growth rate of cash flows after the forecast period. It is used in the perpetuity formula to estimate the value of cash flows beyond the forecast period. The formula for calculating the terminal value (TV) based on perpetuity growth is:
                        <br />
                        <code>
                            TV = Final Year Cash Flow * (1 + g) / (r - g)
                        </code>
                        <ul>
                            <li>
                            TV: Terminal Value
                            </li>
                            <li>
                            g: Perpetuity Growth Rate
                            </li>
                            <li>
                            r: Discount Rate
                            </li>
                        </ul>
                        </li>
                        <li>
                        <strong>Calculation Process:</strong> To perform a DCF valuation, the process typically involves the following steps:
                        <ol>
                            <li>
                            Estimate future cash flows for a specified forecast period.
                            </li>
                            <li>
                            Determine the appropriate discount rate, considering the risk profile of the investment.
                            </li>
                            <li>
                            Calculate the present value of each future cash flow using the discount rate.
                            </li>
                            <li>
                            Sum the present values of all projected cash flows and the terminal value to arrive at the total present value or intrinsic value of the investment.
                            </li>
                        </ol>
                        </li>
                        <li>
                        <strong>Sensitivity Analysis:</strong> DCF models are sensitive to changes in key assumptions, such as the discount rate, growth rates, and cash flow projections. Sensitivity analysis involves testing how changes in these assumptions affect the valuation result, helping to assess the investment&apos;s sensitivity to different scenarios.
                        </li>
                        <li>
                        <strong>Limitations:</strong> DCF valuations rely heavily on the accuracy of cash flow projections and the choice of discount rate. Additionally, DCF models may not fully account for unpredictable events or changes in market conditions. As such, they are just one tool among many for investment analysis, and results should be interpreted with a critical eye.
                        </li>
                    </ol>
                    </div>
                </div>
            </div>
            <Provider store={store} >
                <PersistGate loading={null} persistor={persistor}>
                    <Discounter />
                </PersistGate>
            </Provider>
            <SparkleButton3 />
        </div>
    )
}
export default DiscountedCashFlow